name: Decompile APK with JADX

on:
  workflow_dispatch:
  push:
    paths:
      - "pocket.apk"

jobs:
  decompile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Download latest JADX
        run: |
          # Obtener la última versión disponible
          LATEST_VERSION=$(curl -s https://api.github.com/repos/skylot/jadx/releases/latest | grep '"tag_name"' | head -1 | cut -d'"' -f4)
          echo "Downloading JADX $LATEST_VERSION"
          wget "https://github.com/skylot/jadx/releases/download/${LATEST_VERSION}/jadx-${LATEST_VERSION}.zip"
          unzip "jadx-${LATEST_VERSION}.zip"
          chmod +x jadx/bin/jadx

      - name: Decompile APK
        run: |
          mkdir output
          ./jadx/bin/jadx -d output pocket.apk

      - name: Compress result
        run: |
          zip -r pocket_decompiled.zip output

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pocket-apk-decompiled
          path: pocket_decompiled.zip
